// Generated by `npm run db:pull` (drizzle-kit pull) from the local Supabase database.
// Do not edit by hand: change the schema with a migration in supabase/migrations, then re-run.
/* eslint-disable */
import { authUsers as users } from 'drizzle-orm/supabase';
import { pgTable, index, foreignKey, pgPolicy, serial, integer, timestamp, unique, check, uuid, text, numeric, jsonb, date, boolean, smallint, primaryKey, pgSequence, pgEnum } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"

export const event_status = pgEnum("event_status", ['created', 'pre-bracket', 'bracket', 'completed'])
export const lane_status = pgEnum("lane_status", ['idle', 'occupied', 'maintenance'])
export const league_admin_role = pgEnum("league_admin_role", ['owner', 'admin', 'scorer'])
export const match_status = pgEnum("match_status", ['pending', 'ready', 'in_progress', 'completed'])
export const pool_type = pgEnum("pool_type", ['A', 'B'])
export const qualification_status = pgEnum("qualification_status", ['not_started', 'in_progress', 'completed'])
export const registration_status = pgEnum("registration_status", ['registered', 'paid', 'withdrawn'])
export const stat_type = pgEnum("stat_type", ['qualification_avg', 'match_win_pct', 'putts_made', 'frames_played', 'streak_best', 'qualification_total', 'match_points', 'win_count', 'loss_count', 'overtime_wins', 'overtime_losses', 'avg_points_per_frame', 'total_events_played', 'best_qualification_score', 'perfect_frames', 'total_participants', 'avg_qualification_score', 'highest_match_score', 'total_matches_played'])

export const player_number_seq = pgSequence("player_number_seq", {  startWith: "1", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })

export const bracket_group = pgTable("bracket_group", {
	id: serial().primaryKey().notNull(),
	stage_id: integer().notNull(),
	number: integer().notNull(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_bracket_group_stage").using("btree", table.stage_id.asc().nullsLast().op("int4_ops")),
	foreignKey({
			columns: [table.stage_id],
			foreignColumns: [bracket_stage.id],
			name: "bracket_group_stage_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("Enable read for admins or bracket events", { as: "permissive", for: "select", to: ["anon", "authenticated"], using: sql`((EXISTS ( SELECT 1
   FROM (bracket_stage s
     JOIN events e ON ((e.id = s.tournament_id)))
  WHERE ((s.id = bracket_group.stage_id) AND ((e.status = 'bracket'::event_status) OR (e.status = 'completed'::event_status))))) OR (EXISTS ( SELECT 1
   FROM bracket_stage s
  WHERE ((s.id = bracket_group.stage_id) AND is_tournament_admin(s.tournament_id)))))` }),
]);

export const bracket_round = pgTable("bracket_round", {
	id: serial().primaryKey().notNull(),
	stage_id: integer().notNull(),
	group_id: integer().notNull(),
	number: integer().notNull(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_bracket_round_group").using("btree", table.group_id.asc().nullsLast().op("int4_ops")),
	index("idx_bracket_round_stage").using("btree", table.stage_id.asc().nullsLast().op("int4_ops")),
	foreignKey({
			columns: [table.group_id],
			foreignColumns: [bracket_group.id],
			name: "bracket_round_group_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.stage_id],
			foreignColumns: [bracket_stage.id],
			name: "bracket_round_stage_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("Enable read for admins or bracket events", { as: "permissive", for: "select", to: ["anon", "authenticated"], using: sql`((EXISTS ( SELECT 1
   FROM (bracket_stage s
     JOIN events e ON ((e.id = s.tournament_id)))
  WHERE ((s.id = bracket_round.stage_id) AND ((e.status = 'bracket'::event_status) OR (e.status = 'completed'::event_status))))) OR (EXISTS ( SELECT 1
   FROM bracket_stage s
  WHERE ((s.id = bracket_round.stage_id) AND is_tournament_admin(s.tournament_id)))))` }),
]);

export const event_placements = pgTable("event_placements", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	event_id: uuid().notNull(),
	team_id: uuid().notNull(),
	placement: integer().notNull(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_event_placements_event").using("btree", table.event_id.asc().nullsLast().op("uuid_ops")),
	index("idx_event_placements_team").using("btree", table.team_id.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.event_id],
			foreignColumns: [events.id],
			name: "event_placements_event_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.team_id],
			foreignColumns: [teams.id],
			name: "event_placements_team_id_fkey"
		}).onDelete("cascade"),
	unique("event_placements_event_id_team_id_key").on(table.event_id, table.team_id),
	pgPolicy("Enable read for all", { as: "permissive", for: "select", to: ["anon", "authenticated"], using: sql`true` }),
	check("event_placements_placement_check", sql`placement > 0`),
]);

export const event_players = pgTable("event_players", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	event_id: uuid().notNull(),
	player_id: uuid().notNull(),
	payment_type: text(),
	pool: pool_type(),
	qualification_seed: integer(),
	pfa_score: numeric({ precision: 5, scale:  2 }),
	scoring_method: text(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_event_players_event").using("btree", table.event_id.asc().nullsLast().op("uuid_ops")),
	index("idx_event_players_player").using("btree", table.player_id.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.event_id],
			foreignColumns: [events.id],
			name: "event_players_event_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.player_id],
			foreignColumns: [players.id],
			name: "event_players_player_id_fkey"
		}),
	unique("event_players_event_id_player_id_key").on(table.event_id, table.player_id),
	pgPolicy("Enable read for admins or scoring events", { as: "permissive", for: "select", to: ["anon", "authenticated"], using: sql`((EXISTS ( SELECT 1
   FROM events e
  WHERE ((e.id = event_players.event_id) AND ((e.status = 'bracket'::event_status) OR (e.status = 'completed'::event_status) OR ((e.status = 'pre-bracket'::event_status) AND (e.qualification_round_enabled = true)))))) OR is_league_admin_for_event(event_id))` }),
	check("event_players_payment_type_check", sql`payment_type = ANY (ARRAY['cash'::text, 'electronic'::text])`),
	check("event_players_scoring_method_check", sql`scoring_method = ANY (ARRAY['qualification'::text, 'pfa'::text, 'default'::text])`),
]);

export const rate_limits = pgTable("rate_limits", {
	key: text().primaryKey().notNull(),
	count: integer().notNull(),
	reset_at: timestamp({ withTimezone: true, mode: 'string' }).notNull(),
}, (table) => [
	index("idx_rate_limits_reset_at").using("btree", table.reset_at.asc().nullsLast().op("timestamptz_ops")),
]);

export const teams = pgTable("teams", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	event_id: uuid().notNull(),
	seed: integer(),
	pool_combo: text(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_teams_event").using("btree", table.event_id.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.event_id],
			foreignColumns: [events.id],
			name: "teams_event_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("Enable read for admins or bracket events", { as: "permissive", for: "select", to: ["anon", "authenticated"], using: sql`((EXISTS ( SELECT 1
   FROM events e
  WHERE ((e.id = teams.event_id) AND ((e.status = 'bracket'::event_status) OR (e.status = 'completed'::event_status))))) OR is_league_admin_for_event(event_id))` }),
]);

export const bracket_stage = pgTable("bracket_stage", {
	id: serial().primaryKey().notNull(),
	tournament_id: uuid().notNull(),
	name: text().notNull(),
	type: text().notNull(),
	settings: jsonb().default({}).notNull(),
	number: integer().default(1).notNull(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_bracket_stage_tournament").using("btree", table.tournament_id.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.tournament_id],
			foreignColumns: [events.id],
			name: "bracket_stage_tournament_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("Enable read for admins or bracket events", { as: "permissive", for: "select", to: ["anon", "authenticated"], using: sql`((EXISTS ( SELECT 1
   FROM events e
  WHERE ((e.id = bracket_stage.tournament_id) AND ((e.status = 'bracket'::event_status) OR (e.status = 'completed'::event_status))))) OR is_tournament_admin(tournament_id))` }),
	check("bracket_stage_type_check", sql`type = ANY (ARRAY['single_elimination'::text, 'double_elimination'::text, 'round_robin'::text])`),
]);

export const league_stats = pgTable("league_stats", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	league_id: uuid().notNull(),
	stat_type: stat_type().notNull(),
	value: numeric().notNull(),
	computed_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_league_stats_league").using("btree", table.league_id.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.league_id],
			foreignColumns: [leagues.id],
			name: "league_stats_league_id_fkey"
		}).onDelete("cascade"),
	unique("league_stats_league_id_stat_type_computed_at_key").on(table.league_id, table.stat_type, table.computed_at),
	pgPolicy("Enable public read for league stats", { as: "permissive", for: "select", to: ["anon", "authenticated"], using: sql`true` }),
]);

export const event_statistics = pgTable("event_statistics", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	event_id: uuid().notNull(),
	stat_type: stat_type().notNull(),
	value: numeric().notNull(),
	computed_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_event_statistics_event").using("btree", table.event_id.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.event_id],
			foreignColumns: [events.id],
			name: "event_statistics_event_id_fkey"
		}).onDelete("cascade"),
	unique("event_statistics_event_id_stat_type_computed_at_key").on(table.event_id, table.stat_type, table.computed_at),
	pgPolicy("Enable public read for event statistics", { as: "permissive", for: "select", to: ["anon", "authenticated"], using: sql`true` }),
]);

export const players = pgTable("players", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	player_number: integer().default(sql`nextval('player_number_seq'::regclass)`).notNull(),
	full_name: text().notNull(),
	nickname: text(),
	email: text(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	default_pool: pool_type(),
}, (table) => [
	index("idx_players_full_name").using("gin", table.full_name.asc().nullsLast().op("gin_trgm_ops")),
	unique("players_player_number_key").on(table.player_number),
	pgPolicy("Enable public read for players", { as: "permissive", for: "select", to: ["anon", "authenticated"], using: sql`true` }),
]);

export const leagues = pgTable("leagues", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	name: text().notNull(),
	city: text(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	unique("leagues_name_city_key").on(table.name, table.city),
	pgPolicy("Public read leagues", { as: "permissive", for: "select", to: ["anon", "authenticated"], using: sql`true` }),
	pgPolicy("Enable read access for league admins", { as: "permissive", for: "select", to: ["public"] }),
]);

export const league_admins = pgTable("league_admins", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	league_id: uuid().notNull(),
	user_id: uuid().notNull(),
	role: league_admin_role().default('admin').notNull(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_league_admins_league_id").using("btree", table.league_id.asc().nullsLast().op("uuid_ops")),
	index("idx_league_admins_user_id").using("btree", table.user_id.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.league_id],
			foreignColumns: [leagues.id],
			name: "league_admins_league_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.user_id],
			foreignColumns: [users.id],
			name: "league_admins_user_id_fkey"
		}).onDelete("cascade"),
	unique("league_admins_league_id_user_id_key").on(table.league_id, table.user_id),
	pgPolicy("Enable read access for league admins", { as: "permissive", for: "select", to: ["public"], using: sql`((user_id = ( SELECT auth.uid() AS uid)) OR is_league_admin(league_id, ( SELECT auth.uid() AS uid)))` }),
]);

export const lanes = pgTable("lanes", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	event_id: uuid().notNull(),
	label: text().notNull(),
	status: lane_status().default('idle').notNull(),
}, (table) => [
	foreignKey({
			columns: [table.event_id],
			foreignColumns: [events.id],
			name: "lanes_event_id_fkey"
		}).onDelete("cascade"),
	unique("lanes_event_id_label_key").on(table.event_id, table.label),
	pgPolicy("Enable read for admins or bracket events", { as: "permissive", for: "select", to: ["anon", "authenticated"], using: sql`((EXISTS ( SELECT 1
   FROM events e
  WHERE ((e.id = lanes.event_id) AND (e.status = 'bracket'::event_status)))) OR (EXISTS ( SELECT 1
   FROM (events e
     JOIN league_admins la ON ((la.league_id = e.league_id)))
  WHERE ((e.id = lanes.event_id) AND (la.user_id = ( SELECT auth.uid() AS uid))))))` }),
]);

export const events = pgTable("events", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	league_id: uuid().notNull(),
	event_date: date().notNull(),
	location: text(),
	lane_count: integer().notNull(),
	putt_distance_ft: numeric({ precision: 5, scale:  2 }).notNull(),
	access_code: text().notNull(),
	bonus_point_enabled: boolean().default(true).notNull(),
	qualification_round_enabled: boolean().default(false).notNull(),
	bracket_frame_count: integer().default(5).notNull(),
	qualification_frame_count: integer().default(5).notNull(),
	double_grand_final: boolean().default(true).notNull(),
	entry_fee_per_player: numeric({ precision: 8, scale:  2 }).default('NULL'),
	admin_fees: numeric({ precision: 8, scale:  2 }).default('NULL'),
	admin_fee_per_player: numeric({ precision: 8, scale:  2 }).default('NULL'),
	payout_pool_override: numeric({ precision: 8, scale:  2 }).default('NULL'),
	payout_structure: jsonb(),
	status: event_status().default('created').notNull(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_events_league_date").using("btree", table.league_id.asc().nullsLast().op("date_ops"), table.event_date.desc().nullsFirst().op("date_ops")),
	foreignKey({
			columns: [table.league_id],
			foreignColumns: [leagues.id],
			name: "events_league_id_fkey"
		}).onDelete("cascade"),
	unique("events_access_code_key").on(table.access_code),
	pgPolicy("Enable read for admins or scoring events", { as: "permissive", for: "select", to: ["anon", "authenticated"], using: sql`((status = 'bracket'::event_status) OR (status = 'completed'::event_status) OR ((status = 'pre-bracket'::event_status) AND (qualification_round_enabled = true)) OR (EXISTS ( SELECT 1
   FROM league_admins
  WHERE ((league_admins.league_id = events.league_id) AND (league_admins.user_id = ( SELECT auth.uid() AS uid))))))` }),
	check("access_code_normalized", sql`access_code = lower(TRIM(BOTH FROM access_code))`),
	check("events_bracket_frame_count_check", sql`(bracket_frame_count > 0) AND (bracket_frame_count <= 10)`),
	check("events_lane_count_check", sql`lane_count > 0`),
	check("events_qualification_frame_count_check", sql`(qualification_frame_count > 0) AND (qualification_frame_count <= 10)`),
]);

export const bracket_match = pgTable("bracket_match", {
	id: serial().primaryKey().notNull(),
	stage_id: integer().notNull(),
	group_id: integer().notNull(),
	round_id: integer().notNull(),
	number: integer().notNull(),
	child_count: integer().default(0).notNull(),
	status: integer().default(0).notNull(),
	opponent1: jsonb(),
	opponent2: jsonb(),
	lane_id: uuid(),
	lane_assigned_at: timestamp({ withTimezone: true, mode: 'string' }),
	event_id: uuid(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_bracket_match_event").using("btree", table.event_id.asc().nullsLast().op("uuid_ops")),
	index("idx_bracket_match_group").using("btree", table.group_id.asc().nullsLast().op("int4_ops")),
	index("idx_bracket_match_lane").using("btree", table.lane_id.asc().nullsLast().op("uuid_ops")),
	index("idx_bracket_match_round").using("btree", table.round_id.asc().nullsLast().op("int4_ops")),
	index("idx_bracket_match_stage").using("btree", table.stage_id.asc().nullsLast().op("int4_ops")),
	index("idx_bracket_match_status").using("btree", table.status.asc().nullsLast().op("int4_ops")),
	foreignKey({
			columns: [table.event_id],
			foreignColumns: [events.id],
			name: "bracket_match_event_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.group_id],
			foreignColumns: [bracket_group.id],
			name: "bracket_match_group_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.lane_id],
			foreignColumns: [lanes.id],
			name: "bracket_match_lane_id_fkey"
		}),
	foreignKey({
			columns: [table.round_id],
			foreignColumns: [bracket_round.id],
			name: "bracket_match_round_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.stage_id],
			foreignColumns: [bracket_stage.id],
			name: "bracket_match_stage_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("Enable read for admins or bracket events", { as: "permissive", for: "select", to: ["anon", "authenticated"], using: sql`((EXISTS ( SELECT 1
   FROM events e
  WHERE ((e.id = bracket_match.event_id) AND ((e.status = 'bracket'::event_status) OR (e.status = 'completed'::event_status))))) OR (EXISTS ( SELECT 1
   FROM bracket_stage s
  WHERE ((s.id = bracket_match.stage_id) AND is_tournament_admin(s.tournament_id)))))` }),
]);

export const bracket_match_game = pgTable("bracket_match_game", {
	id: serial().primaryKey().notNull(),
	stage_id: integer().notNull(),
	parent_id: integer().notNull(),
	number: integer().notNull(),
	status: integer().default(0).notNull(),
	opponent1: jsonb(),
	opponent2: jsonb(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_bracket_match_game_parent").using("btree", table.parent_id.asc().nullsLast().op("int4_ops")),
	foreignKey({
			columns: [table.parent_id],
			foreignColumns: [bracket_match.id],
			name: "bracket_match_game_parent_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.stage_id],
			foreignColumns: [bracket_stage.id],
			name: "bracket_match_game_stage_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("Enable read access for league admins", { as: "permissive", for: "select", to: ["public"], using: sql`(EXISTS ( SELECT 1
   FROM bracket_stage s
  WHERE ((s.id = bracket_match_game.stage_id) AND is_tournament_admin(s.tournament_id))))` }),
]);

export const bracket_participant = pgTable("bracket_participant", {
	id: serial().primaryKey().notNull(),
	tournament_id: uuid().notNull(),
	name: text().notNull(),
	team_id: uuid(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_bracket_participant_team").using("btree", table.team_id.asc().nullsLast().op("uuid_ops")),
	index("idx_bracket_participant_tournament").using("btree", table.tournament_id.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.team_id],
			foreignColumns: [teams.id],
			name: "bracket_participant_team_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.tournament_id],
			foreignColumns: [events.id],
			name: "bracket_participant_tournament_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("Enable read for admins or bracket events", { as: "permissive", for: "select", to: ["anon", "authenticated"], using: sql`((EXISTS ( SELECT 1
   FROM events e
  WHERE ((e.id = bracket_participant.tournament_id) AND ((e.status = 'bracket'::event_status) OR (e.status = 'completed'::event_status))))) OR is_tournament_admin(tournament_id))` }),
]);

export const qualification_rounds = pgTable("qualification_rounds", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	event_id: uuid().notNull(),
	frame_count: integer().default(5).notNull(),
	created_by: uuid(),
	status: qualification_status().default('not_started').notNull(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_qualification_rounds_event").using("btree", table.event_id.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.created_by],
			foreignColumns: [users.id],
			name: "qualification_rounds_created_by_fkey"
		}),
	foreignKey({
			columns: [table.event_id],
			foreignColumns: [events.id],
			name: "qualification_rounds_event_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("Enable read for admins or pre-bracket", { as: "permissive", for: "select", to: ["anon", "authenticated"], using: sql`((EXISTS ( SELECT 1
   FROM events e
  WHERE ((e.id = qualification_rounds.event_id) AND (e.status = 'pre-bracket'::event_status) AND (e.qualification_round_enabled = true)))) OR is_league_admin_for_event(event_id))` }),
]);

export const qualification_frames = pgTable("qualification_frames", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	qualification_round_id: uuid().notNull(),
	event_id: uuid().notNull(),
	event_player_id: uuid().notNull(),
	frame_number: integer().notNull(),
	putts_made: integer().notNull(),
	points_earned: integer().notNull(),
	recorded_by: uuid(),
	recorded_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_qualification_frames_event").using("btree", table.event_id.asc().nullsLast().op("uuid_ops")),
	index("idx_qualification_frames_event_player").using("btree", table.event_player_id.asc().nullsLast().op("uuid_ops")),
	index("idx_qualification_frames_round").using("btree", table.qualification_round_id.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.event_id],
			foreignColumns: [events.id],
			name: "qualification_frames_event_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.event_player_id],
			foreignColumns: [event_players.id],
			name: "qualification_frames_event_player_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.qualification_round_id],
			foreignColumns: [qualification_rounds.id],
			name: "qualification_frames_qualification_round_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.recorded_by],
			foreignColumns: [users.id],
			name: "qualification_frames_recorded_by_fkey"
		}),
	unique("qualification_frames_event_player_id_frame_number_key").on(table.event_player_id, table.frame_number),
	pgPolicy("Enable read for admins or pre-bracket", { as: "permissive", for: "select", to: ["anon", "authenticated"], using: sql`((EXISTS ( SELECT 1
   FROM events e
  WHERE ((e.id = qualification_frames.event_id) AND (e.status = 'pre-bracket'::event_status) AND (e.qualification_round_enabled = true)))) OR is_league_admin_for_event(event_id))` }),
	check("qualification_frames_frame_number_check", sql`frame_number > 0`),
	check("qualification_frames_points_earned_check", sql`(points_earned >= 0) AND (points_earned <= 4)`),
	check("qualification_frames_putts_made_check", sql`(putts_made >= 0) AND (putts_made <= 3)`),
]);

export const match_frames = pgTable("match_frames", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	bracket_match_id: integer(),
	frame_number: integer().notNull(),
	is_overtime: boolean().default(false).notNull(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_match_frames_bracket_match").using("btree", table.bracket_match_id.asc().nullsLast().op("int4_ops")),
	foreignKey({
			columns: [table.bracket_match_id],
			foreignColumns: [bracket_match.id],
			name: "match_frames_bracket_match_id_fkey"
		}).onDelete("cascade"),
	unique("match_frames_bracket_match_id_frame_number_key").on(table.bracket_match_id, table.frame_number),
	pgPolicy("Enable read for all users", { as: "permissive", for: "select", to: ["anon", "authenticated"], using: sql`true` }),
]);

export const frame_results = pgTable("frame_results", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	match_frame_id: uuid().notNull(),
	event_player_id: uuid().notNull(),
	bracket_match_id: integer(),
	putts_made: integer().notNull(),
	points_earned: integer().notNull(),
	order_in_frame: smallint().notNull(),
	recorded_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_frame_results_bracket_match").using("btree", table.bracket_match_id.asc().nullsLast().op("int4_ops")),
	index("idx_frame_results_event_player_recorded").using("btree", table.event_player_id.asc().nullsLast().op("uuid_ops"), table.recorded_at.asc().nullsLast().op("timestamptz_ops")),
	index("idx_frame_results_match_frame").using("btree", table.match_frame_id.asc().nullsLast().op("uuid_ops")),
	index("idx_frame_results_match_frame_player").using("btree", table.match_frame_id.asc().nullsLast().op("uuid_ops"), table.event_player_id.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.bracket_match_id],
			foreignColumns: [bracket_match.id],
			name: "frame_results_bracket_match_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.event_player_id],
			foreignColumns: [event_players.id],
			name: "frame_results_event_player_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.match_frame_id],
			foreignColumns: [match_frames.id],
			name: "frame_results_match_frame_id_fkey"
		}).onDelete("cascade"),
	unique("frame_results_match_frame_id_event_player_id_key").on(table.match_frame_id, table.event_player_id),
	pgPolicy("Enable read for all users", { as: "permissive", for: "select", to: ["anon", "authenticated"], using: sql`true` }),
	check("frame_results_order_in_frame_check", sql`order_in_frame >= 1`),
	check("frame_results_points_earned_check", sql`(points_earned >= 0) AND (points_earned <= 4)`),
	check("frame_results_putts_made_check", sql`(putts_made >= 0) AND (putts_made <= 3)`),
]);

export const player_statistics = pgTable("player_statistics", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	player_id: uuid().notNull(),
	league_id: uuid().notNull(),
	event_id: uuid(),
	stat_type: stat_type().notNull(),
	value: numeric().notNull(),
	computed_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_player_statistics_event").using("btree", table.event_id.asc().nullsLast().op("uuid_ops")),
	index("idx_player_statistics_league").using("btree", table.league_id.asc().nullsLast().op("uuid_ops")),
	index("idx_player_statistics_player").using("btree", table.player_id.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.event_id],
			foreignColumns: [events.id],
			name: "player_statistics_event_id_fkey"
		}).onDelete("set null"),
	foreignKey({
			columns: [table.league_id],
			foreignColumns: [leagues.id],
			name: "player_statistics_league_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.player_id],
			foreignColumns: [players.id],
			name: "player_statistics_player_id_fkey"
		}).onDelete("cascade"),
	unique("player_statistics_player_id_event_id_stat_type_key").on(table.player_id, table.event_id, table.stat_type),
	pgPolicy("Enable public read for player statistics", { as: "permissive", for: "select", to: ["anon", "authenticated"], using: sql`true` }),
]);

export const team_members = pgTable("team_members", {
	team_id: uuid().notNull(),
	event_player_id: uuid().notNull(),
	role: text().notNull(),
	joined_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_team_members_event_player").using("btree", table.event_player_id.asc().nullsLast().op("uuid_ops")),
	index("idx_team_members_team").using("btree", table.team_id.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.event_player_id],
			foreignColumns: [event_players.id],
			name: "team_members_event_player_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.team_id],
			foreignColumns: [teams.id],
			name: "team_members_team_id_fkey"
		}).onDelete("cascade"),
	primaryKey({ columns: [table.team_id, table.event_player_id], name: "team_members_pkey"}),
	pgPolicy("Enable read for admins or bracket events", { as: "permissive", for: "select", to: ["anon", "authenticated"], using: sql`((EXISTS ( SELECT 1
   FROM (teams t
     JOIN events e ON ((e.id = t.event_id)))
  WHERE ((t.id = team_members.team_id) AND ((e.status = 'bracket'::event_status) OR (e.status = 'completed'::event_status))))) OR (EXISTS ( SELECT 1
   FROM teams t
  WHERE ((t.id = team_members.team_id) AND is_league_admin_for_event(t.event_id)))))` }),
	check("team_members_role_check", sql`role = ANY (ARRAY['A_pool'::text, 'B_pool'::text, 'alternate'::text])`),
]);
