#!/usr/bin/env node
// Regenerate lib/db/schema.ts from the local database (`npm run db:pull`), or with
// `--check`, fail if the committed schema.ts differs from what the database would
// generate (`npm run db:check`, run in CI after migrations are applied).
//
// Supabase migrations are the source of truth; schema.ts only mirrors them for typing.
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const target = join(root, 'lib/db/schema.ts');
const check = process.argv.includes('--check');

const HEADER =
  '// Generated by `npm run db:pull` (drizzle-kit pull) from the local Supabase database.\n' +
  '// Do not edit by hand: change the schema with a migration in supabase/migrations, then re-run.\n' +
  '/* eslint-disable */\n' +
  // drizzle-kit emits references to auth.users (outside schemaFilter) without defining it.
  "import { authUsers as users } from 'drizzle-orm/supabase';\n";

/**
 * Make the output independent of the database's history. drizzle-kit emits tables and
 * their constraints in catalog order (which differs between a long-lived and a fresh
 * database), and with two policies on one table it can attach a USING clause to the
 * wrong one. RLS policies are owned by the Supabase migrations and tested by pgTAP, so
 * they are dropped here; tables, table constraints and imports are sorted.
 */
function normalize(source) {
  const sortItems = (block) =>
    block.replace(/\(table\) => \[\n([\s\S]*)\n\]\);$/, (_, body) => {
      const items = body
        .split(/\n(?=\t\S)/)
        .filter((item) => !item.startsWith('\tpgPolicy('))
        .sort();
      return `(table) => [\n${items.join('\n')}\n]);`;
    });

  const isTable = (block) => /^export const \w+ = pgTable\(/.test(block);
  const blocks = source.trim().split(/\n(?=export const )/).map((b) => b.trim());
  const head = blocks.filter((b) => !isTable(b));
  const tables = blocks.filter(isTable).map(sortItems).sort();

  const text = [...head, ...tables].join('\n\n') + '\n';
  const usesPolicy = text.includes('pgPolicy(');
  return text.replace(/import \{([^}]*)\} from "drizzle-orm\/pg-core"/, (_, names) => {
    const sorted = names
      .split(',')
      .map((n) => n.trim())
      .filter((n) => n && (usesPolicy || n !== 'pgPolicy'))
      .sort();
    return `import { ${sorted.join(', ')} } from "drizzle-orm/pg-core"`;
  });
}

const out = mkdtempSync(join(tmpdir(), 'drizzle-pull-'));
try {
  execFileSync('npx', ['drizzle-kit', 'pull'], {
    cwd: root,
    env: { ...process.env, DRIZZLE_OUT: out },
    stdio: check ? 'pipe' : 'inherit',
  });

  const generated = HEADER + normalize(readFileSync(join(out, 'schema.ts'), 'utf8'));

  if (check) {
    const current = existsSync(target) ? readFileSync(target, 'utf8') : '';
    if (current !== generated) {
      const fresh = join(out, 'expected-schema.ts');
      writeFileSync(fresh, generated);
      try {
        execFileSync('git', ['diff', '--no-index', '--no-color', target, fresh], { stdio: 'inherit' });
      } catch {
        // git diff exits 1 when the files differ
      }
      console.error('lib/db/schema.ts is out of date with the database. Run `npm run db:pull` and commit the result.');
      process.exit(1);
    }
    console.log('lib/db/schema.ts matches the database.');
  } else {
    writeFileSync(target, generated);
    console.log(`Wrote ${target}`);
  }
} finally {
  rmSync(out, { recursive: true, force: true });
}
